### ISSUE TITLE
Camera example

### ISSUE THREAD

**Issue by jannispl** [jean343/Node-OpenMAX#3]
I am currently struggling to get the camera component working. Could you provide a small example how to set it up?

**Comment by jean343** [comment]
Hello,

Thanks for the interest. I did get a hand on a pi. Are you using the special camera such as https://www.adafruit.com/product/1367?

**Comment by jannispl** [comment]
@jean343 Yes, I'm using the camera module, v2 however.

**Comment by jean343** [comment]
I have added three examples under https://github.com/jean343/Node-OpenMAX/tree/master/examples/ts

The tunnel examples requires less CPU as the buffers don't go through JavaScript.

The Pipe examples allows you to do image processing on the frames in JavaScript.

**Comment by jean343** [comment]
I have added lots of camera setting examples in the test cases:
https://github.com/jean343/Node-OpenMAX/blob/master/spec/components/CameraEffectsSpec.ts
