### ISSUE TITLE
A few issues with the examples

### ISSUE THREAD

**Issue by skerit** [jean343/Node-OpenMAX#6]
So I tried the `PerfRender` file you suggested to test out scaling and such, and that works! :+1: 

I am running into a few issues, though:

- In its original configuration `PerfRender.js` was set to 3 rows and 4 columns. My screen isn't HD, so I had to set that to 2x2, otherwise I got a black screen after the first 2 renders started drawing (some kind of "out of bounds" issue?)

- `PerfGLGrid.js` is only showing a blue screen. The `texture` property of all the `ws (WritableFilter)` instances is always `undefined` :/ (And yeah, I also changed the rows & columns here)

- When I try `PerfGLGrid.js` a few times in a row (only ever getting the dark blue screen), I get an `Error: OMX_GetState() returned error: OMX_ErrorInsufficientResources`. `PerfRender.js` will now only show 1 video, instead of 4. To get everything back to normal again I have to reboot the pi.

Also:

-  `SimpleVideoDecoderRender.js` plays the video 'till the end
-  `SimpleVideoDecoderRenderTunner.js` stops just about after the "presents..." title, never exiting the script. Seems like it's caused by `tunnel`-ing the data into the renderer instead of using `pipe`

**Comment by jean343** [comment]
About the 'out of bound' issue, try changing the `width` and `height` to the size of your monitor, I do adjust the videos to that dimension.

Any example with `gl` in the name uses the experimental OpenGL library and they are not fully functional, I should add experimental in their name. I do believe they leak GL ressources, and you have to restart the PI to get them working again. It's worst if we kill the software with `ctrl+C`, try letting the video finish instead.

I will try `SimpleVideoDecoderRenderTunnel.js` when I get a chance. I believe it worked last time. Try restarting your PI and try again.

**Comment by jean343** [comment]
If you don't mind, I will close this bug, if you have more info, please feel free to re-open.
