### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by sledesm** [jean343/Node-OpenMAX#7]
How could I contribute to this project?
I have made a simple example which allows to stream the camera frames into pngs very quickly. there are other applications online, but they are either bulky or very slow.

**Comment by jean343** [comment]
Thanks so much for the feedback!
I always like examples, and I would like to add it. Either make a fork and send me a pull request, or write the code somewhere and I will add it.
Did you use the Camera and ImageWriter?

JP

**Comment by sledesm** [comment]
I used Camera and ImageEncoder. I do not know about ImageWriter.

**Comment by jean343** [comment]
I saw your request, getting my PI from my pile and I will try!

**Comment by sledesm** [comment]
I just added another commit, to solve the problem of the buffer length on the stream. Here is a code snippet from the sample application that I am building 

```
    var ws = require('stream').Writable();
    var recBuffer = null;
    ws._write = function (chunk, enc, next) {
        var nextPart = chunk;
        if (chunk.onBufferDone) {
            if (chunk.usedLength !== undefined && chunk.usedLength < chunk.length) {
                // console.log("Getting buffer to smaller size")
                nextPart = chunk.slice(0, chunk.usedLength);
            }
            if (!recBuffer) {
                recBuffer = nextPart;
            } else {
                recBuffer = concat([recBuffer, nextPart]);
            }
            riseCore.emit("omx-camera-frame", recBuffer);
            recBuffer = null;
            chunk.onBufferDone();
        } else {
            if (recBuffer) {
                recBuffer = Buffer.concat([recBuffer, chunk]);
            } else
                recBuffer = Buffer.from(chunk);
        }
        next();
    };
```

**Comment by jean343** [comment]
I merged it, however it does not work for me, `_write` isn't called.

**Comment by sledesm** [comment]
Hi,

I am using the code of npm 1.6.0

I went to the node_modules/openmax/dist/perf, and copied there the
CameraEncode.js example and run it there. It works for me. I run it after
running CameraPipe


Regards,

Santi.

**Comment by sledesm** [comment]
Hi

Could you make it work?

I post you a screenshot of what I'm doing right now. I am using 4 raspberry
pis and websockets. I get around 25 fps sending jpg frames and around 6%
cpu in the raspberry pi.

Would you be so kind to publish a new version of the module with the latest
change? It is needed for the jpg transmission because otherwise the system
cannot know if a frame has finished or not when encoding using discrete
frames coming out of the Encoding component.

Regards,

Santi.

**Comment by jean343** [comment]
I did not get it to work, I get an invalid parameter exception... It might be a problem with my PI.
Your stats are pretty impressive, PIes are cool!

No problem, I just did push 1.6.1

JP

**Comment by sledesm** [comment]
Txs!
