### ISSUE TITLE
Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by DiegOrtega** [jean343/Node-OpenMAX#9]
This happened while running the module here: https://npm.runkit.com/openmax

Error: Could not locate the bindings file. Tried:
 → /app/available_modules/1511633220000/openmax/build/Node_OMX.node
 → /app/available_modules/1511633220000/openmax/build/Debug/Node_OMX.node
 → /app/available_modules/1511633220000/openmax/build/Release/Node_OMX.node
 → /app/available_modules/1511633220000/openmax/out/Debug/Node_OMX.node
 → /app/available_modules/1511633220000/openmax/Debug/Node_OMX.node
 → /app/available_modules/1511633220000/openmax/out/Release/Node_OMX.node
 → /app/available_modules/1511633220000/openmax/Release/Node_OMX.node
 → /app/available_modules/1511633220000/openmax/build/default/Node_OMX.node
 → /app/available_modules/1511633220000/openmax/compiled/8.9.0/linux/x64/Node_OMX.node

**Comment by jean343** [comment]
Thanks for the feedback.
The module has to be compiled on a raspberry pi and cannot be run in your browser. Even if it did work, I do not think it would display video.
